---
- hosts: localhost
  become: yes
  become_method: sudo 
  tasks: 
    - name: Group admin  
      group: 
        name: admin
        state: present

    - name: Group admin2  
      group: 
        name: admin2
        state: present
    
    - name: Group admin3  
      group: 
        name: admin3
        state: present
